// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Rental is an object representing the database table.
type Rental struct {
	RentalID    int       `boil:"rental_id" json:"rental_id" toml:"rental_id" yaml:"rental_id"`
	RentalDate  time.Time `boil:"rental_date" json:"rental_date" toml:"rental_date" yaml:"rental_date"`
	InventoryID int32     `boil:"inventory_id" json:"inventory_id" toml:"inventory_id" yaml:"inventory_id"`
	CustomerID  int       `boil:"customer_id" json:"customer_id" toml:"customer_id" yaml:"customer_id"`
	ReturnDate  null.Time `boil:"return_date" json:"return_date,omitempty" toml:"return_date" yaml:"return_date,omitempty"`
	StaffID     int8      `boil:"staff_id" json:"staff_id" toml:"staff_id" yaml:"staff_id"`
	LastUpdate  time.Time `boil:"last_update" json:"last_update" toml:"last_update" yaml:"last_update"`

	R *rentalR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L rentalL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var RentalColumns = struct {
	RentalID    string
	RentalDate  string
	InventoryID string
	CustomerID  string
	ReturnDate  string
	StaffID     string
	LastUpdate  string
}{
	RentalID:    "rental_id",
	RentalDate:  "rental_date",
	InventoryID: "inventory_id",
	CustomerID:  "customer_id",
	ReturnDate:  "return_date",
	StaffID:     "staff_id",
	LastUpdate:  "last_update",
}

var RentalTableColumns = struct {
	RentalID    string
	RentalDate  string
	InventoryID string
	CustomerID  string
	ReturnDate  string
	StaffID     string
	LastUpdate  string
}{
	RentalID:    "rental.rental_id",
	RentalDate:  "rental.rental_date",
	InventoryID: "rental.inventory_id",
	CustomerID:  "rental.customer_id",
	ReturnDate:  "rental.return_date",
	StaffID:     "rental.staff_id",
	LastUpdate:  "rental.last_update",
}

// Generated where

var RentalWhere = struct {
	RentalID    whereHelperint
	RentalDate  whereHelpertime_Time
	InventoryID whereHelperint32
	CustomerID  whereHelperint
	ReturnDate  whereHelpernull_Time
	StaffID     whereHelperint8
	LastUpdate  whereHelpertime_Time
}{
	RentalID:    whereHelperint{field: "`rental`.`rental_id`"},
	RentalDate:  whereHelpertime_Time{field: "`rental`.`rental_date`"},
	InventoryID: whereHelperint32{field: "`rental`.`inventory_id`"},
	CustomerID:  whereHelperint{field: "`rental`.`customer_id`"},
	ReturnDate:  whereHelpernull_Time{field: "`rental`.`return_date`"},
	StaffID:     whereHelperint8{field: "`rental`.`staff_id`"},
	LastUpdate:  whereHelpertime_Time{field: "`rental`.`last_update`"},
}

// RentalRels is where relationship names are stored.
var RentalRels = struct {
	Customer  string
	Inventory string
	Staff     string
	Payments  string
}{
	Customer:  "Customer",
	Inventory: "Inventory",
	Staff:     "Staff",
	Payments:  "Payments",
}

// rentalR is where relationships are stored.
type rentalR struct {
	Customer  *Customer    `boil:"Customer" json:"Customer" toml:"Customer" yaml:"Customer"`
	Inventory *Inventory   `boil:"Inventory" json:"Inventory" toml:"Inventory" yaml:"Inventory"`
	Staff     *Staff       `boil:"Staff" json:"Staff" toml:"Staff" yaml:"Staff"`
	Payments  PaymentSlice `boil:"Payments" json:"Payments" toml:"Payments" yaml:"Payments"`
}

// NewStruct creates a new relationship struct
func (*rentalR) NewStruct() *rentalR {
	return &rentalR{}
}

func (r *rentalR) GetCustomer() *Customer {
	if r == nil {
		return nil
	}
	return r.Customer
}

func (r *rentalR) GetInventory() *Inventory {
	if r == nil {
		return nil
	}
	return r.Inventory
}

func (r *rentalR) GetStaff() *Staff {
	if r == nil {
		return nil
	}
	return r.Staff
}

func (r *rentalR) GetPayments() PaymentSlice {
	if r == nil {
		return nil
	}
	return r.Payments
}

// rentalL is where Load methods for each relationship are stored.
type rentalL struct{}

var (
	rentalAllColumns            = []string{"rental_id", "rental_date", "inventory_id", "customer_id", "return_date", "staff_id", "last_update"}
	rentalColumnsWithoutDefault = []string{"rental_date", "inventory_id", "customer_id", "return_date", "staff_id"}
	rentalColumnsWithDefault    = []string{"rental_id", "last_update"}
	rentalPrimaryKeyColumns     = []string{"rental_id"}
	rentalGeneratedColumns      = []string{}
)

type (
	// RentalSlice is an alias for a slice of pointers to Rental.
	// This should almost always be used instead of []Rental.
	RentalSlice []*Rental
	// RentalHook is the signature for custom Rental hook methods
	RentalHook func(context.Context, boil.ContextExecutor, *Rental) error

	rentalQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	rentalType                 = reflect.TypeOf(&Rental{})
	rentalMapping              = queries.MakeStructMapping(rentalType)
	rentalPrimaryKeyMapping, _ = queries.BindMapping(rentalType, rentalMapping, rentalPrimaryKeyColumns)
	rentalInsertCacheMut       sync.RWMutex
	rentalInsertCache          = make(map[string]insertCache)
	rentalUpdateCacheMut       sync.RWMutex
	rentalUpdateCache          = make(map[string]updateCache)
	rentalUpsertCacheMut       sync.RWMutex
	rentalUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var rentalAfterSelectMu sync.Mutex
var rentalAfterSelectHooks []RentalHook

var rentalBeforeInsertMu sync.Mutex
var rentalBeforeInsertHooks []RentalHook
var rentalAfterInsertMu sync.Mutex
var rentalAfterInsertHooks []RentalHook

var rentalBeforeUpdateMu sync.Mutex
var rentalBeforeUpdateHooks []RentalHook
var rentalAfterUpdateMu sync.Mutex
var rentalAfterUpdateHooks []RentalHook

var rentalBeforeDeleteMu sync.Mutex
var rentalBeforeDeleteHooks []RentalHook
var rentalAfterDeleteMu sync.Mutex
var rentalAfterDeleteHooks []RentalHook

var rentalBeforeUpsertMu sync.Mutex
var rentalBeforeUpsertHooks []RentalHook
var rentalAfterUpsertMu sync.Mutex
var rentalAfterUpsertHooks []RentalHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Rental) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Rental) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Rental) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Rental) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Rental) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Rental) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Rental) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Rental) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Rental) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range rentalAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddRentalHook registers your hook function for all future operations.
func AddRentalHook(hookPoint boil.HookPoint, rentalHook RentalHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		rentalAfterSelectMu.Lock()
		rentalAfterSelectHooks = append(rentalAfterSelectHooks, rentalHook)
		rentalAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		rentalBeforeInsertMu.Lock()
		rentalBeforeInsertHooks = append(rentalBeforeInsertHooks, rentalHook)
		rentalBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		rentalAfterInsertMu.Lock()
		rentalAfterInsertHooks = append(rentalAfterInsertHooks, rentalHook)
		rentalAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		rentalBeforeUpdateMu.Lock()
		rentalBeforeUpdateHooks = append(rentalBeforeUpdateHooks, rentalHook)
		rentalBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		rentalAfterUpdateMu.Lock()
		rentalAfterUpdateHooks = append(rentalAfterUpdateHooks, rentalHook)
		rentalAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		rentalBeforeDeleteMu.Lock()
		rentalBeforeDeleteHooks = append(rentalBeforeDeleteHooks, rentalHook)
		rentalBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		rentalAfterDeleteMu.Lock()
		rentalAfterDeleteHooks = append(rentalAfterDeleteHooks, rentalHook)
		rentalAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		rentalBeforeUpsertMu.Lock()
		rentalBeforeUpsertHooks = append(rentalBeforeUpsertHooks, rentalHook)
		rentalBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		rentalAfterUpsertMu.Lock()
		rentalAfterUpsertHooks = append(rentalAfterUpsertHooks, rentalHook)
		rentalAfterUpsertMu.Unlock()
	}
}

// One returns a single rental record from the query.
func (q rentalQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Rental, error) {
	o := &Rental{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for rental")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Rental records from the query.
func (q rentalQuery) All(ctx context.Context, exec boil.ContextExecutor) (RentalSlice, error) {
	var o []*Rental

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Rental slice")
	}

	if len(rentalAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Rental records in the query.
func (q rentalQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count rental rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q rentalQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if rental exists")
	}

	return count > 0, nil
}

// Customer pointed to by the foreign key.
func (o *Rental) Customer(mods ...qm.QueryMod) customerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`customer_id` = ?", o.CustomerID),
	}

	queryMods = append(queryMods, mods...)

	return Customers(queryMods...)
}

// Inventory pointed to by the foreign key.
func (o *Rental) Inventory(mods ...qm.QueryMod) inventoryQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`inventory_id` = ?", o.InventoryID),
	}

	queryMods = append(queryMods, mods...)

	return Inventories(queryMods...)
}

// Staff pointed to by the foreign key.
func (o *Rental) Staff(mods ...qm.QueryMod) staffQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`staff_id` = ?", o.StaffID),
	}

	queryMods = append(queryMods, mods...)

	return Staffs(queryMods...)
}

// Payments retrieves all the payment's Payments with an executor.
func (o *Rental) Payments(mods ...qm.QueryMod) paymentQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("`payment`.`rental_id`=?", o.RentalID),
	)

	return Payments(queryMods...)
}

// LoadCustomer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (rentalL) LoadCustomer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRental interface{}, mods queries.Applicator) error {
	var slice []*Rental
	var object *Rental

	if singular {
		var ok bool
		object, ok = maybeRental.(*Rental)
		if !ok {
			object = new(Rental)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRental))
			}
		}
	} else {
		s, ok := maybeRental.(*[]*Rental)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRental))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &rentalR{}
		}
		args[object.CustomerID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &rentalR{}
			}

			args[obj.CustomerID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`customer`),
		qm.WhereIn(`customer.customer_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Customer")
	}

	var resultSlice []*Customer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Customer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for customer")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for customer")
	}

	if len(customerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Customer = foreign
		if foreign.R == nil {
			foreign.R = &customerR{}
		}
		foreign.R.Rentals = append(foreign.R.Rentals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CustomerID == foreign.CustomerID {
				local.R.Customer = foreign
				if foreign.R == nil {
					foreign.R = &customerR{}
				}
				foreign.R.Rentals = append(foreign.R.Rentals, local)
				break
			}
		}
	}

	return nil
}

// LoadInventory allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (rentalL) LoadInventory(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRental interface{}, mods queries.Applicator) error {
	var slice []*Rental
	var object *Rental

	if singular {
		var ok bool
		object, ok = maybeRental.(*Rental)
		if !ok {
			object = new(Rental)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRental))
			}
		}
	} else {
		s, ok := maybeRental.(*[]*Rental)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRental))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &rentalR{}
		}
		args[object.InventoryID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &rentalR{}
			}

			args[obj.InventoryID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`inventory`),
		qm.WhereIn(`inventory.inventory_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Inventory")
	}

	var resultSlice []*Inventory
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Inventory")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for inventory")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for inventory")
	}

	if len(inventoryAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Inventory = foreign
		if foreign.R == nil {
			foreign.R = &inventoryR{}
		}
		foreign.R.Rentals = append(foreign.R.Rentals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.InventoryID == foreign.InventoryID {
				local.R.Inventory = foreign
				if foreign.R == nil {
					foreign.R = &inventoryR{}
				}
				foreign.R.Rentals = append(foreign.R.Rentals, local)
				break
			}
		}
	}

	return nil
}

// LoadStaff allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (rentalL) LoadStaff(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRental interface{}, mods queries.Applicator) error {
	var slice []*Rental
	var object *Rental

	if singular {
		var ok bool
		object, ok = maybeRental.(*Rental)
		if !ok {
			object = new(Rental)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRental))
			}
		}
	} else {
		s, ok := maybeRental.(*[]*Rental)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRental))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &rentalR{}
		}
		args[object.StaffID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &rentalR{}
			}

			args[obj.StaffID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`staff`),
		qm.WhereIn(`staff.staff_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Staff")
	}

	var resultSlice []*Staff
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Staff")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for staff")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for staff")
	}

	if len(staffAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Staff = foreign
		if foreign.R == nil {
			foreign.R = &staffR{}
		}
		foreign.R.Rentals = append(foreign.R.Rentals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.StaffID == foreign.StaffID {
				local.R.Staff = foreign
				if foreign.R == nil {
					foreign.R = &staffR{}
				}
				foreign.R.Rentals = append(foreign.R.Rentals, local)
				break
			}
		}
	}

	return nil
}

// LoadPayments allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (rentalL) LoadPayments(ctx context.Context, e boil.ContextExecutor, singular bool, maybeRental interface{}, mods queries.Applicator) error {
	var slice []*Rental
	var object *Rental

	if singular {
		var ok bool
		object, ok = maybeRental.(*Rental)
		if !ok {
			object = new(Rental)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeRental))
			}
		}
	} else {
		s, ok := maybeRental.(*[]*Rental)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeRental)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeRental))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &rentalR{}
		}
		args[object.RentalID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &rentalR{}
			}
			args[obj.RentalID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`payment`),
		qm.WhereIn(`payment.rental_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load payment")
	}

	var resultSlice []*Payment
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice payment")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on payment")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for payment")
	}

	if len(paymentAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Payments = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &paymentR{}
			}
			foreign.R.Rental = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.RentalID, foreign.RentalID) {
				local.R.Payments = append(local.R.Payments, foreign)
				if foreign.R == nil {
					foreign.R = &paymentR{}
				}
				foreign.R.Rental = local
				break
			}
		}
	}

	return nil
}

// SetCustomer of the rental to the related item.
// Sets o.R.Customer to related.
// Adds o to related.R.Rentals.
func (o *Rental) SetCustomer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Customer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `rental` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"customer_id"}),
		strmangle.WhereClause("`", "`", 0, rentalPrimaryKeyColumns),
	)
	values := []interface{}{related.CustomerID, o.RentalID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CustomerID = related.CustomerID
	if o.R == nil {
		o.R = &rentalR{
			Customer: related,
		}
	} else {
		o.R.Customer = related
	}

	if related.R == nil {
		related.R = &customerR{
			Rentals: RentalSlice{o},
		}
	} else {
		related.R.Rentals = append(related.R.Rentals, o)
	}

	return nil
}

// SetInventory of the rental to the related item.
// Sets o.R.Inventory to related.
// Adds o to related.R.Rentals.
func (o *Rental) SetInventory(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Inventory) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `rental` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"inventory_id"}),
		strmangle.WhereClause("`", "`", 0, rentalPrimaryKeyColumns),
	)
	values := []interface{}{related.InventoryID, o.RentalID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.InventoryID = related.InventoryID
	if o.R == nil {
		o.R = &rentalR{
			Inventory: related,
		}
	} else {
		o.R.Inventory = related
	}

	if related.R == nil {
		related.R = &inventoryR{
			Rentals: RentalSlice{o},
		}
	} else {
		related.R.Rentals = append(related.R.Rentals, o)
	}

	return nil
}

// SetStaff of the rental to the related item.
// Sets o.R.Staff to related.
// Adds o to related.R.Rentals.
func (o *Rental) SetStaff(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Staff) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `rental` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"staff_id"}),
		strmangle.WhereClause("`", "`", 0, rentalPrimaryKeyColumns),
	)
	values := []interface{}{related.StaffID, o.RentalID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.StaffID = related.StaffID
	if o.R == nil {
		o.R = &rentalR{
			Staff: related,
		}
	} else {
		o.R.Staff = related
	}

	if related.R == nil {
		related.R = &staffR{
			Rentals: RentalSlice{o},
		}
	} else {
		related.R.Rentals = append(related.R.Rentals, o)
	}

	return nil
}

// AddPayments adds the given related objects to the existing relationships
// of the rental, optionally inserting them as new records.
// Appends related to o.R.Payments.
// Sets related.R.Rental appropriately.
func (o *Rental) AddPayments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Payment) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.RentalID, o.RentalID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE `payment` SET %s WHERE %s",
				strmangle.SetParamNames("`", "`", 0, []string{"rental_id"}),
				strmangle.WhereClause("`", "`", 0, paymentPrimaryKeyColumns),
			)
			values := []interface{}{o.RentalID, rel.PaymentID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.RentalID, o.RentalID)
		}
	}

	if o.R == nil {
		o.R = &rentalR{
			Payments: related,
		}
	} else {
		o.R.Payments = append(o.R.Payments, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &paymentR{
				Rental: o,
			}
		} else {
			rel.R.Rental = o
		}
	}
	return nil
}

// SetPayments removes all previously related items of the
// rental replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.Rental's Payments accordingly.
// Replaces o.R.Payments with related.
// Sets related.R.Rental's Payments accordingly.
func (o *Rental) SetPayments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Payment) error {
	query := "update `payment` set `rental_id` = null where `rental_id` = ?"
	values := []interface{}{o.RentalID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.Payments {
			queries.SetScanner(&rel.RentalID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.Rental = nil
		}
		o.R.Payments = nil
	}

	return o.AddPayments(ctx, exec, insert, related...)
}

// RemovePayments relationships from objects passed in.
// Removes related items from R.Payments (uses pointer comparison, removal does not keep order)
// Sets related.R.Rental.
func (o *Rental) RemovePayments(ctx context.Context, exec boil.ContextExecutor, related ...*Payment) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.RentalID, nil)
		if rel.R != nil {
			rel.R.Rental = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("rental_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.Payments {
			if rel != ri {
				continue
			}

			ln := len(o.R.Payments)
			if ln > 1 && i < ln-1 {
				o.R.Payments[i] = o.R.Payments[ln-1]
			}
			o.R.Payments = o.R.Payments[:ln-1]
			break
		}
	}

	return nil
}

// Rentals retrieves all the records using an executor.
func Rentals(mods ...qm.QueryMod) rentalQuery {
	mods = append(mods, qm.From("`rental`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`rental`.*"})
	}

	return rentalQuery{q}
}

// FindRental retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindRental(ctx context.Context, exec boil.ContextExecutor, rentalID int, selectCols ...string) (*Rental, error) {
	rentalObj := &Rental{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `rental` where `rental_id`=?", sel,
	)

	q := queries.Raw(query, rentalID)

	err := q.Bind(ctx, exec, rentalObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from rental")
	}

	if err = rentalObj.doAfterSelectHooks(ctx, exec); err != nil {
		return rentalObj, err
	}

	return rentalObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Rental) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rental provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rentalColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	rentalInsertCacheMut.RLock()
	cache, cached := rentalInsertCache[key]
	rentalInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			rentalAllColumns,
			rentalColumnsWithDefault,
			rentalColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(rentalType, rentalMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(rentalType, rentalMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `rental` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `rental` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `rental` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, rentalPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into rental")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.RentalID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rentalMapping["rental_id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.RentalID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rental")
	}

CacheNoHooks:
	if !cached {
		rentalInsertCacheMut.Lock()
		rentalInsertCache[key] = cache
		rentalInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Rental.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Rental) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	rentalUpdateCacheMut.RLock()
	cache, cached := rentalUpdateCache[key]
	rentalUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			rentalAllColumns,
			rentalPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update rental, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `rental` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, rentalPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(rentalType, rentalMapping, append(wl, rentalPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update rental row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for rental")
	}

	if !cached {
		rentalUpdateCacheMut.Lock()
		rentalUpdateCache[key] = cache
		rentalUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q rentalQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for rental")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for rental")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o RentalSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rentalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `rental` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rentalPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in rental slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all rental")
	}
	return rowsAff, nil
}

var mySQLRentalUniqueColumns = []string{
	"rental_id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Rental) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no rental provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(rentalColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLRentalUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	rentalUpsertCacheMut.RLock()
	cache, cached := rentalUpsertCache[key]
	rentalUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			rentalAllColumns,
			rentalColumnsWithDefault,
			rentalColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			rentalAllColumns,
			rentalPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert rental, could not build update column list")
		}

		ret := strmangle.SetComplement(rentalAllColumns, strmangle.SetIntersect(insert, update))

		cache.query = buildUpsertQueryMySQL(dialect, "`rental`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `rental` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(rentalType, rentalMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(rentalType, rentalMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for rental")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.RentalID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == rentalMapping["rental_id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(rentalType, rentalMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for rental")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for rental")
	}

CacheNoHooks:
	if !cached {
		rentalUpsertCacheMut.Lock()
		rentalUpsertCache[key] = cache
		rentalUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Rental record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Rental) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Rental provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), rentalPrimaryKeyMapping)
	sql := "DELETE FROM `rental` WHERE `rental_id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from rental")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for rental")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q rentalQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no rentalQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rental")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rental")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o RentalSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(rentalBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rentalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `rental` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rentalPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from rental slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for rental")
	}

	if len(rentalAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Rental) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindRental(ctx, exec, o.RentalID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *RentalSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := RentalSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), rentalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `rental`.* FROM `rental` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, rentalPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in RentalSlice")
	}

	*o = slice

	return nil
}

// RentalExists checks if the Rental row exists.
func RentalExists(ctx context.Context, exec boil.ContextExecutor, rentalID int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `rental` where `rental_id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, rentalID)
	}
	row := exec.QueryRowContext(ctx, sql, rentalID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if rental exists")
	}

	return exists, nil
}

// Exists checks if the Rental row exists.
func (o *Rental) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return RentalExists(ctx, exec, o.RentalID)
}
