// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// StaffList is an object representing the database table.
type StaffList struct {
	ID      int8        `boil:"ID" json:"ID" toml:"ID" yaml:"ID"`
	Name    null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	Address string      `boil:"address" json:"address" toml:"address" yaml:"address"`
	ZipCode null.String `boil:"zip code" json:"zip code,omitempty" toml:"zip code" yaml:"zip code,omitempty"`
	Phone   string      `boil:"phone" json:"phone" toml:"phone" yaml:"phone"`
	City    string      `boil:"city" json:"city" toml:"city" yaml:"city"`
	Country string      `boil:"country" json:"country" toml:"country" yaml:"country"`
	SID     int8        `boil:"SID" json:"SID" toml:"SID" yaml:"SID"`
}

var StaffListColumns = struct {
	ID      string
	Name    string
	Address string
	ZipCode string
	Phone   string
	City    string
	Country string
	SID     string
}{
	ID:      "ID",
	Name:    "name",
	Address: "address",
	ZipCode: "zip code",
	Phone:   "phone",
	City:    "city",
	Country: "country",
	SID:     "SID",
}

var StaffListTableColumns = struct {
	ID      string
	Name    string
	Address string
	ZipCode string
	Phone   string
	City    string
	Country string
	SID     string
}{
	ID:      "staff_list.ID",
	Name:    "staff_list.name",
	Address: "staff_list.address",
	ZipCode: "staff_list.zip code",
	Phone:   "staff_list.phone",
	City:    "staff_list.city",
	Country: "staff_list.country",
	SID:     "staff_list.SID",
}

// Generated where

var StaffListWhere = struct {
	ID      whereHelperint8
	Name    whereHelpernull_String
	Address whereHelperstring
	ZipCode whereHelpernull_String
	Phone   whereHelperstring
	City    whereHelperstring
	Country whereHelperstring
	SID     whereHelperint8
}{
	ID:      whereHelperint8{field: "`staff_list`.`ID`"},
	Name:    whereHelpernull_String{field: "`staff_list`.`name`"},
	Address: whereHelperstring{field: "`staff_list`.`address`"},
	ZipCode: whereHelpernull_String{field: "`staff_list`.`zip code`"},
	Phone:   whereHelperstring{field: "`staff_list`.`phone`"},
	City:    whereHelperstring{field: "`staff_list`.`city`"},
	Country: whereHelperstring{field: "`staff_list`.`country`"},
	SID:     whereHelperint8{field: "`staff_list`.`SID`"},
}

var (
	staffListAllColumns            = []string{"ID", "name", "address", "zip code", "phone", "city", "country", "SID"}
	staffListColumnsWithoutDefault = []string{"name", "address", "zip code", "phone", "city", "country", "SID"}
	staffListColumnsWithDefault    = []string{"ID"}
	staffListPrimaryKeyColumns     = []string{}
	staffListGeneratedColumns      = []string{}
)

type (
	// StaffListSlice is an alias for a slice of pointers to StaffList.
	// This should almost always be used instead of []StaffList.
	StaffListSlice []*StaffList
	// StaffListHook is the signature for custom StaffList hook methods
	StaffListHook func(context.Context, boil.ContextExecutor, *StaffList) error

	staffListQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	staffListType           = reflect.TypeOf(&StaffList{})
	staffListMapping        = queries.MakeStructMapping(staffListType)
	staffListInsertCacheMut sync.RWMutex
	staffListInsertCache    = make(map[string]insertCache)
	staffListUpdateCacheMut sync.RWMutex
	staffListUpdateCache    = make(map[string]updateCache)
	staffListUpsertCacheMut sync.RWMutex
	staffListUpsertCache    = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
	// These are used in some views
	_ = fmt.Sprintln("")
	_ = reflect.Int
	_ = strings.Builder{}
	_ = sync.Mutex{}
	_ = strmangle.Plural("")
	_ = strconv.IntSize
)

var staffListAfterSelectMu sync.Mutex
var staffListAfterSelectHooks []StaffListHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *StaffList) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range staffListAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddStaffListHook registers your hook function for all future operations.
func AddStaffListHook(hookPoint boil.HookPoint, staffListHook StaffListHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		staffListAfterSelectMu.Lock()
		staffListAfterSelectHooks = append(staffListAfterSelectHooks, staffListHook)
		staffListAfterSelectMu.Unlock()
	}
}

// One returns a single staffList record from the query.
func (q staffListQuery) One(ctx context.Context, exec boil.ContextExecutor) (*StaffList, error) {
	o := &StaffList{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for staff_list")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all StaffList records from the query.
func (q staffListQuery) All(ctx context.Context, exec boil.ContextExecutor) (StaffListSlice, error) {
	var o []*StaffList

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to StaffList slice")
	}

	if len(staffListAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all StaffList records in the query.
func (q staffListQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count staff_list rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q staffListQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if staff_list exists")
	}

	return count > 0, nil
}

// StaffLists retrieves all the records using an executor.
func StaffLists(mods ...qm.QueryMod) staffListQuery {
	mods = append(mods, qm.From("`staff_list`"))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"`staff_list`.*"})
	}

	return staffListQuery{q}
}
