// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var ViewNames = struct {
	ActorInfo              string
	CustomerList           string
	FilmList               string
	NicerButSlowerFilmList string
	SalesByFilmCategory    string
	SalesByStore           string
	StaffList              string
}{
	ActorInfo:              "actor_info",
	CustomerList:           "customer_list",
	FilmList:               "film_list",
	NicerButSlowerFilmList: "nicer_but_slower_film_list",
	SalesByFilmCategory:    "sales_by_film_category",
	SalesByStore:           "sales_by_store",
	StaffList:              "staff_list",
}
